pipeline {
    agent { node { label 'maven' } } 
    stages {
        stage('build') {
            steps {
                script {
                    openshift.withCluster('default') {
                        def ocDir = tool "oc"
                        withEnv(["PATH+OC=${ocDir}"]) {
                            def status = openshift.startBuild('weather-on-shift')
                            status.logs('-f')
                        }
                    }
                }
            }
        }
        stage('deploy') {
            steps {
                script {
                    openshift.withCluster('default') {
                        def ocDir = tool "oc"
                        withEnv(["PATH+OC=${ocDir}"]) {
                            def selector = openshift.selector("dc/weather-on-shift")
                            def result = selector.rollout().latest()
                            echo "${result.out}"
						}
                    }    
                }
            }
        }
    }
}

