node('maven') {
  stage("build") {
    echo "Building Weather On Shift!"
    openshiftBuild buildConfig: "weather-on-shift", showBuildLogs: "true", verbose: "verbose"
  }
  stage("deploy") {
    echo "Deploying Weather On Shift"
    openshiftDeploy deploymentConfig: "weather-on-shift"
  }
}
