apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: weather-on-shift
  name: weather-on-shift
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: weather-on-shift:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/jbornemann/weather-on-shift
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: go-s2i:17
        namespace: myproject
    type: Source
  triggers: {}
