apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: weather-on-shift
  name: weather-on-shift
spec:
  replicas: 1
  selector:
    app: weather-on-shift
    deploymentconfig: weather-on-shift
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: weather-on-shift
        deploymentconfig: weather-on-shift
    spec:
      containers:
      - image: 172.30.1.1:5000/myproject/weather-on-shift:latest
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        name: weather-on-shift
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /data/weather
          name: weather-on-shift-secret-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: weather-on-shift-secret-volume
        secret:
          defaultMode: 420
          secretName: weather-on-shift-secret
  triggers: {}
