apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  generation: 4
  labels:
    run: weather-on-shift
  name: weather-on-shift
spec:
  replicas: 1
  selector:
    matchLabels:
      run: weather-on-shift
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: weather-on-shift
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: bornemannjs/weather-on-shift:latest
        imagePullPolicy: Always
        name: weather-on-shift
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/weather
          name: weather-on-shift-secret-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: weather-on-shift-secret-volume
        secret:
          defaultMode: 420
          secretName: weather-on-shift-secret
status:
