apiVersion: v1
kind: Service
metadata:
  name: open-weathermap-service
  annotations:
    service.alpha.openshift.io/dependencies: '[{"name":"weather-on-shift-service","namespace":"","kind":"Service"}]'
  labels:
      app: weather-on-shift
spec:
  externalName: api.openweathermap.org
  ports: null
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}
