apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: open-weathermap-service
spec:
  externalName: api.openweathermap.org
  ports: null
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}
