apiVersion: v1
kind: List
metadata:
    labels:
        app: weather-on-shift
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: go-s2i
    labels:
        app: weather-on-shift
  spec:
    tags:
    - name: "17"
      from:
        kind: DockerImage
        name: bornemannjs/go-s2i:17
      importPolicy: {}
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: weather-on-shift
    labels:
      app: weather-on-shift
  spec:
    tags:
    - name: "latest"
      from:
        kind: DockerImage
        name: weather-on-shift:latest
      importPolicy: {}
      referencePolicy:
        type: ""
