apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations: {}
    creationTimestamp: null
    generation: 1
    name: go-s2i
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/myproject/go-s2i:17
      generation: 1
      importPolicy: {}
      name: "17"
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: weather-on-shift
    name: weather-on-shift
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/myproject/weather-on-shift:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
kind: List
metadata: {}
