apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: weather-on-shift
  name: weather-on-shift-pipeline
spec:
  nodeSelector: null
  source:
    git:
      uri: https://github.com/jbornemann/weather-on-shift 
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: pipeline
