apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: weather-on-shift
  name: weather-on-shift-pipeline
spec:
  nodeSelector: null
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: pipeline
