apiVersion: v1
kind: Service
metadata:
    name: weather-on-shift-service
    labels:
        app: weather-on-shift
spec:
    selector:                  
        app: weather-on-shift
    ports:
        - name: 8080-tcp
          protocol: TCP 
          port: 8080
          targetPort: 8080 
